chisnbal_user:
    resource: "@ChisnbalBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

chisnbal_color:
    resource: "@ChisnbalBundle/Resources/config/routing/color.yml"
    prefix:   /admin/color

chisnbal_size:
    resource: "@ChisnbalBundle/Resources/config/routing/size.yml"
    prefix:   /admin/size

chisnbal_category:
    resource: "@ChisnbalBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

chisnbal_product:
    resource: "@ChisnbalBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

chisnbal_fotodetalle:
    resource: "@ChisnbalBundle/Resources/config/routing/fotodetalle.yml"
    prefix:   /admin/fotodetalle

chisnbal_cart:
    resource: "@ChisnbalBundle/Resources/config/routing/cart.yml"
    prefix:   /admin/cart

chisnbal_cartitem:
    resource: "@ChisnbalBundle/Resources/config/routing/cartitem.yml"
    prefix:   /admin/cartitem

chisnbal_orderinfo:
    resource: "@ChisnbalBundle/Resources/config/routing/orderinfo.yml"
    prefix:   /admin/orderinfo

chisnbal_orderitem:
    resource: "@ChisnbalBundle/Resources/config/routing/orderitem.yml"
    prefix:   /admin/orderitem

celina_select:
    resource: "@ChisnbalBundle/Resources/config/routing/select.yml"
    prefix: /admin/select

chisnbal_homepage:
    path:     /
    defaults: { _controller: ChisnbalBundle:Default:index }

chisnbal_homepage_admin:
    path:     /admin
    defaults: { _controller: ChisnbalBundle:Default:backEnd }

chisnbal_quiensomos:
    path:     /quiensomos
    defaults: { _controller: ChisnbalBundle:Default:quiensomos }

chisnbal_product_list:
    path:     /productList/{categoryId}
    defaults: { _controller: ChisnbalBundle:Default:productList }

chisnbal_product_list_new:
    path:     /productListNew
    defaults: { _controller: ChisnbalBundle:Default:productListNew }

chisnbal_fotodetalle_list:
    path:     /fotodetalle/{productId}
    defaults: { _controller: ChisnbalBundle:Default:productDetalle }

chisnbal_carrito:
    path:     /carrito
    defaults: { _controller: ChisnbalBundle:Default:cart }

chisnbal_guestinfo:
    path:     /orderinfo
    defaults: { _controller: ChisnbalBundle:Default:guestinfo }

cart_update:
    path:     /cartupdate
    defaults: { _controller: ChisnbalBundle:Default:ajaxUpdate }

chisnbal_cartToOrderinfo:
    path:     /cartToOrderinfo
    defaults: { _controller: ChisnbalBundle:Order:cartToOrderinfo }

chisnbal_addToCart:
    path:     /addToCart
    defaults: { _controller: ChisnbalBundle:Default:addToCart }

chisnbal_orderclient:
    path:     /orderclient
    defaults: { _controller: ChisnbalBundle:Order:orderclient }

chisnbal_productlistclient:
    path:     /orderclient/orderitems/{orderInfoId}
    defaults: { _controller: ChisnbalBundle:Order:productlistclient }