chisnbal_homepage:
    path:     /
    defaults: { _controller: ChisnbalBundle:Default:index }

chisnbal_product_list:
    path:     /productList
    defaults: { _controller: ChisnbalBundle:Default:productList }

chisnbal_fotodetalle_list:
    path:     /fotodetalle
    defaults: { _controller: ChisnbalBundle:Default:productDetalle }

chisnbal_cart:
    path:     /carrito
    defaults: { _controller: ChisnbalBundle:Default:cart }