<?php

namespace ChisnbalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FotodetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotodetalleRepository extends EntityRepository
{
}
