cartitem_index:
    path:     /
    defaults: { _controller: "ChisnbalBundle:CartItem:index" }
    methods:  GET

cartitem_show:
    path:     /{id}/show
    defaults: { _controller: "ChisnbalBundle:CartItem:show" }
    methods:  GET

cartitem_new:
    path:     /new
    defaults: { _controller: "ChisnbalBundle:CartItem:new" }
    methods:  [GET, POST]

cartitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChisnbalBundle:CartItem:edit" }
    methods:  [GET, POST]

cartitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChisnbalBundle:CartItem:delete" }
    methods:  DELETE
