color_index:
    path:     /{productId}
    defaults: { _controller: "ChisnbalBundle:Color:index" }
    methods:  GET

color_show:
    path:     /{id}/show
    defaults: { _controller: "ChisnbalBundle:Color:show" }
    methods:  GET

color_new:
    path:     /{productId}/new
    defaults: { _controller: "ChisnbalBundle:Color:new" }
    methods:  [GET, POST]

color_edit:
    path:     /{productId}/{id}/edit
    defaults: { _controller: "ChisnbalBundle:Color:edit" }
    methods:  [GET, POST]

color_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChisnbalBundle:Color:delete" }
    methods:  DELETE
