orderinfo_index:
    path:     /
    defaults: { _controller: "ChisnbalBundle:OrderInfo:index" }
    methods:  GET

orderinfo_show:
    path:     /{id}/show
    defaults: { _controller: "ChisnbalBundle:OrderInfo:show" }
    methods:  GET

orderinfo_new:
    path:     /new
    defaults: { _controller: "ChisnbalBundle:OrderInfo:new" }
    methods:  [GET, POST]

orderinfo_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChisnbalBundle:OrderInfo:edit" }
    methods:  [GET, POST]

orderinfo_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChisnbalBundle:OrderInfo:delete" }
    methods:  DELETE
