select_new:
    path:     /new
    defaults: { _controller: "ChisnbalBundle:Select:selectNew" }

add_new:
    path:     /addnew
    defaults: { _controller: "ChisnbalBundle:Select:addNew" }

delete_new:
    path:     /deletenew/{id}
    defaults: { _controller: "ChisnbalBundle:Select:deleteNew" }